---

- project:
    templates:
      - publish-stx-docs
      - stx-api-ref-jobs
      - stx-release-notes-jobs
      - stx-lint-specfile-jobs
      - stx-build-rpms
    check:
      jobs:
        - openstack-tox-linters
        - openstack-tox-pep8
        - stx-fault-build
    gate:
      jobs:
        - openstack-tox-linters
        - openstack-tox-pep8

# Perform just a build
- job:
    name: stx-fault-build
    parent: tox
    description: Run build for fault
    irrelevant-files:
      - api-ref/*
      - docs/*
      - releasenotes/*
    vars:
      tox_envlist: build

- job:
    name: flock-devstack-fault
    parent: flock-devstack-base-min
    required-projects:
      # - name: starlingx/config
      - name: starlingx/integ
      - name: starlingx/update
    vars:
      tox_envlist: functional
      devstack_services:
        # cgtsclient: true
        fm-common: true
        fm-api: true
        fm-rest-api: true
        fm-mgr: true
      devstack_plugins:
        # config: https://opendev.org/starlingx/config
        fault: https://opendev.org/starlingx/fault
        integ: https://opendev.org/starlingx/integ
        update: https://opendev.org/starlingx/update
